creation_rules:
  - path_regex: "manifests/.*.yaml"
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      B51DED3777E929E187022400A39D7D193673FE6D,
      3DC80C3752A95B8D539B034240559725E3612372
  - path_regex: "talosconfig"
    encrypted_regex: "^key$"
    pgp: >-
      3DC80C3752A95B8D539B034240559725E3612372
  - path_regex: "kubeconfig"
    encrypted_regex: "^client-key-data$"
    pgp: >-
      3DC80C3752A95B8D539B034240559725E3612372
  - path_regex: "secrets.yaml"
    encrypted_regex: "^(secret|bootstraptoken|secretboxencryptionsecret|token|key)$"
    pgp: >-
      3DC80C3752A95B8D539B034240559725E3612372
  - path_regex: "machineconfigs/.*.yaml"
    encrypted_regex: "^(secret|bootstraptoken|secretboxEncryptionSecret|token|key|password)$"
    pgp: >-
      3DC80C3752A95B8D539B034240559725E3612372
