apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/r3dlobst3r/kubelab # replace with your actual repo
  ref:
    branch: main
  secretRef:
    name: flux-system # if using auth; otherwise omit this line
